version: '3'
services:
  mongo:
    image: mongo:bionic
    networks:
      - {{cookiecutter.project_name}}_network
    container_name: "{{cookiecutter.project_name}}_mongo_docker"
    env_file:
     - ./mongo/.env
    volumes:
      - "./mongo/volume:/data/db"
      - "./mongo/dumps:/dumps"
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - "./mongo/.dbshell:/home/mongodb/.dbshell"
  redis:
    image: redis:latest
    networks:
      - {{cookiecutter.project_name}}_network
  app:
    depends_on: [mongo]
    image: {{cookiecutter.project_name}}-flask
    container_name: "{{cookiecutter.project_name}}_app"
    networks:
      - {{cookiecutter.project_name}}_network
    build:
      context: "./backend"
    env_file:
      - ./mongo/.env
      - ./backend/.env
    volumes:
      - "./backend:/app/backend/"
      - "./frontend/dist:/app/backend/templates:ro"
      - "./frontend/dist/static:/app/backend/static:ro"
    command: "python -m backend"


networks:
  {{cookiecutter.project_name}}_network:
    driver: bridge
