version: '3'
services:
  vuecli:
    image: "{{cookiecutter.project_name}}-vue2"
    networks:
      - "{{cookiecutter.project_name}}_network"
    build:
      context: "./frontend"
    volumes:
      - "./frontend:/home/node"
    ports:
      - "{{ cookiecutter.dev_front_end_port }}:8080"
    command: "npm run serve"

  
networks:
  {{cookiecutter.project_name}}_network:
    driver: bridge
